name: Generate Status Badges

on:
  workflow_run:
    workflows: 
      - "LifeSync Regression Tests"
      - "LifeSync Full Test Suite" 
      - "Focus Endpoint Monitor"
      - "API Connectivity Check"
    types:
      - completed
  schedule:
    # Update badges daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-status-badges:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate workflow status badges
      run: |
        echo "# LifeSync Workflow Status Dashboard" > .github/STATUS.md
        echo "" >> .github/STATUS.md
        echo "[![Regression Tests](https://github.com/${{ github.repository }}/actions/workflows/regression-tests.yml/badge.svg)](https://github.com/${{ github.repository }}/actions/workflows/regression-tests.yml)" >> .github/STATUS.md
        echo "[![Full Test Suite](https://github.com/${{ github.repository }}/actions/workflows/full-test-suite.yml/badge.svg)](https://github.com/${{ github.repository }}/actions/workflows/full-test-suite.yml)" >> .github/STATUS.md
        echo "[![Focus Monitor](https://github.com/${{ github.repository }}/actions/workflows/focus-endpoint-monitor.yml/badge.svg)](https://github.com/${{ github.repository }}/actions/workflows/focus-endpoint-monitor.yml)" >> .github/STATUS.md
        echo "[![API Connectivity](https://github.com/${{ github.repository }}/actions/workflows/api-connectivity-check.yml/badge.svg)](https://github.com/${{ github.repository }}/actions/workflows/api-connectivity-check.yml)" >> .github/STATUS.md
        echo "" >> .github/STATUS.md
        echo "## Quick Status Overview" >> .github/STATUS.md
        echo "" >> .github/STATUS.md
        echo "| Workflow | Purpose | Frequency | Critical |" >> .github/STATUS.md
        echo "|----------|---------|-----------|----------|" >> .github/STATUS.md
        echo "| Regression Tests | Smoke tests & Focus endpoints | Every push + Daily | 🔴 High |" >> .github/STATUS.md
        echo "| Full Test Suite | Comprehensive validation | Major changes | 🟡 Medium |" >> .github/STATUS.md
        echo "| Focus Monitor | Focus API monitoring | Every 6 hours | 🔴 High |" >> .github/STATUS.md
        echo "| Connectivity Check | Environment validation | Every 2 hours | 🟠 Medium-High |" >> .github/STATUS.md
        echo "" >> .github/STATUS.md
        echo "## Focus Endpoint Protection 🧘" >> .github/STATUS.md
        echo "" >> .github/STATUS.md
        echo "The Focus Monitor workflow specifically protects against the return of these 404 errors:" >> .github/STATUS.md
        echo "- \`GET /api/focus/profile 404 (Not Found)\`" >> .github/STATUS.md
        echo "- \`GET /api/focus/achievements 404 (Not Found)\`" >> .github/STATUS.md
        echo "- \`GET /api/focus/analytics 404 (Not Found)\`" >> .github/STATUS.md
        echo "" >> .github/STATUS.md
        echo "**Last Updated:** \$(date)" >> .github/STATUS.md

    - name: Commit status updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .github/STATUS.md
        git diff --staged --quiet || git commit -m "Update workflow status badges [skip ci]"
        git push || echo "No changes to push"