#!/bin/bash

# Ad Hoc Distribution for Life Weave
# Install on specific devices (up to 100 devices)

echo "📱 Ad Hoc Distribution Guide for Life Weave"
echo ""
echo "Use this method if you want to install on specific devices without TestFlight."
echo ""
echo "Prerequisites:"
echo "  ✓ Apple Developer Account (paid - $99/year required)"
echo "  ✓ Your partner's device UDID"
echo ""
echo "Steps to follow:"
echo ""
echo "1️⃣ GET YOUR PARTNER'S DEVICE UDID"
echo "   Option A - Via Finder:"
echo "     • Connect their iPhone to your Mac"
echo "     • Open Finder"
echo "     • Select their iPhone in sidebar"
echo "     • Click on the serial number until UDID appears"
echo "     • Right-click → Copy UDID"
echo ""
echo "   Option B - Via Xcode:"
echo "     • Connect their iPhone to your Mac"
echo "     • Open Xcode → Window → Devices and Simulators"
echo "     • Select their device"
echo "     • Copy the 'Identifier' value"
echo ""
echo "2️⃣ REGISTER THE DEVICE"
echo "   • Go to: https://developer.apple.com/account/resources/devices"
echo "   • Click '+' to add a new device"
echo "   • Enter a name (e.g., 'Partner iPhone')"
echo "   • Paste the UDID"
echo "   • Click 'Continue' and 'Register'"
echo ""
echo "3️⃣ CREATE AD HOC PROVISIONING PROFILE"
echo "   • Go to: https://developer.apple.com/account/resources/profiles"
echo "   • Click '+' to create new profile"
echo "   • Select 'Ad Hoc'"
echo "   • Choose your App ID (com.lifesync.app)"
echo "   • Select your distribution certificate"
echo "   • Select the registered devices (including partner's iPhone)"
echo "   • Name it (e.g., 'Life Weave Ad Hoc')"
echo "   • Download the profile"
echo "   • Double-click to install it in Xcode"
echo ""
echo "4️⃣ ARCHIVE WITH AD HOC PROFILE"
echo "   • Xcode will open the project"
echo "   • Select 'Any iOS Device (arm64)'"
echo "   • Product → Archive"
echo "   • When done, click 'Distribute App'"
echo "   • Choose 'Ad Hoc'"
echo "   • Select the Ad Hoc provisioning profile you created"
echo "   • Choose 'Export' and save the .ipa file"
echo ""
echo "5️⃣ INSTALL ON PARTNER'S IPHONE"
echo "   Option A - Via Apple Configurator (Mac):"
echo "     • Install Apple Configurator 2 from Mac App Store"
echo "     • Connect partner's iPhone"
echo "     • Drag the .ipa file onto their device"
echo ""
echo "   Option B - Via Cloud Service:"
echo "     • Upload .ipa to Dropbox/Google Drive"
echo "     • Use a service like diawi.com or install.appcenter.ms"
echo "     • Share the installation link with your partner"
echo "     • They open link on iPhone → Install"
echo ""
echo "LIMITATIONS:"
echo "  ⚠️  Requires paid Apple Developer account ($99/year)"
echo "  ⚠️  Need to register each device individually"
echo "  ⚠️  Maximum 100 devices per year"
echo "  ⚠️  More complex than TestFlight"
echo ""
echo "💡 TIP: TestFlight is easier and free! Use that instead if possible."
echo ""
echo "Building web assets..."
npm run build:skip-typecheck

echo "Syncing with Capacitor..."
npx cap sync ios

echo "Opening Xcode..."
open ios/App/App.xcodeproj
