-- Migration: Add Visa Requirements Table
-- Purpose: Move 2.5MB visa requirements data from bundle to database
-- Date: 2026-02-16
--
-- This migrates visa requirement data from static TypeScript file to Supabase
-- Reduces bundle size by ~2.5MB and enables dynamic querying
--
-- Data source: passport-index-dataset (MIT License)
-- https://github.com/ilyankou/passport-index-dataset
-- 199 passport countries, 39,601 visa requirement entries

-- Create visa requirements table
CREATE TABLE IF NOT EXISTS visa_requirements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  passport_country TEXT NOT NULL,
  destination_country TEXT NOT NULL,
  requirement TEXT NOT NULL CHECK (requirement IN (
    'visa-free',
    'visa-on-arrival',
    'eta',
    'e-visa',
    'visa-required',
    'no-admission'
  )),
  days_allowed INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Unique constraint: one requirement per passport-destination pair
  UNIQUE(passport_country, destination_country)
);

-- Indexes for common query patterns
CREATE INDEX idx_visa_req_passport ON visa_requirements(passport_country);
CREATE INDEX idx_visa_req_destination ON visa_requirements(destination_country);
CREATE INDEX idx_visa_req_requirement ON visa_requirements(requirement);
CREATE INDEX idx_visa_req_passport_requirement ON visa_requirements(passport_country, requirement);

-- RLS policies (public read access, no write access from client)
ALTER TABLE visa_requirements ENABLE ROW LEVEL SECURITY;

-- Anyone can read visa requirements (public data)
CREATE POLICY "Visa requirements are publicly readable"
  ON visa_requirements
  FOR SELECT
  USING (true);

-- No insert/update/delete from client (data managed via migrations/admin)
CREATE POLICY "No client modifications to visa requirements"
  ON visa_requirements
  FOR ALL
  USING (false);

-- Add helpful comment
COMMENT ON TABLE visa_requirements IS 'Global visa requirements database - 199 passport countries, ~39,601 entries. Source: passport-index-dataset (MIT). Updated: January 2025.';

-- Note: Data will be imported via separate SQL file generated by import script
-- Run: npm run import:visa-data (to be created)
